version: "3.8"

services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: wisal-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: wisal
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - wisal-network-dev

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: wisal-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - wisal-network-dev

  # Backend Service (Development)
  backend:
    build:
      context: ./wisal/backend
      dockerfile: Dockerfile.dev
    container_name: wisal-backend-dev
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGODB_URI: mongodb://mongodb:27017/wisal
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-jwt-secret-2025
      JWT_REFRESH_SECRET: dev-jwt-refresh-secret-2025
      FRONTEND_URL: http://localhost:3000
      OPENAI_API_KEY: ${OPENAI_API_KEY:-sk-test-key}
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID:-your_linkedin_client_id}
      LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET:-your_linkedin_client_secret}
      LINKEDIN_CALLBACK_URL: http://localhost:4000/api/auth/linkedin/callback
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./wisal/backend:/app
      - /app/node_modules
    networks:
      - wisal-network-dev

  # Frontend Service (Development)
  frontend:
    build:
      context: ./wisal/frontend
      dockerfile: Dockerfile.dev
    container_name: wisal-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:4000/api
      VITE_SOCKET_URL: http://localhost:4000
    depends_on:
      - backend
    volumes:
      - ./wisal/frontend:/app
      - /app/node_modules
    networks:
      - wisal-network-dev

networks:
  wisal-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev:
